### ISSUE TITLE
需要添加安卓版本支持

### ISSUE THREAD

**Issue by wgll000** [EightDoor/siyuan#3]
### In what scenarios do you need this feature?

有了windos再加个安卓的呗

### Describe the optimal solution

有了windos再加个安卓的呗

### Describe the candidate solution

有了windos再加个安卓的呗

### Other information

有了windos再加个安卓的呗

**Comment by EightDoor** [comment]
我会尽快添加

**Comment by uuuuuuuuuup** [comment]
> 我会尽快添加

老哥 我在另一个项目看到了安卓app打包脚本，但是我没有安装思源需要的环境，您可以run一下脚本之后构建一下吗。这个问题里面：https://github.com/appdev/siyuan-unlock/issues/4#issuecomment-1890360296。

**Comment by uuuuuuuuuup** [comment]
> 我会尽快添加

这个是打包脚本：https://github.com/appdev/siyuan-unlock/blob/master/scripts/android-build.sh

**Comment by EightDoor** [comment]
已打包 查看release [v2.12.4-android Release](https://github.com/EightDoor/siyuan/releases/tag/v2.12.4-android) 
@uuuuuuuuuup
@wgll000
