### ISSUE TITLE
Aarch64 Linux release

### ISSUE THREAD

**Issue by meichthys** [EightDoor/siyuan#5]
### In what scenarios do you need this feature?

This would allow arm based linux machines to run this (like a Macbook M1 running Linux)

### Describe the optimal solution

An aarch64 release

### Other information

If this is better focused at the upstream repository, just let me know and i can request it there.

Thanks for this project!

**Comment by EightDoor** [comment]
If the build version is the same as the original warehouse, and there is no build version in the original warehouse. I have time to try and see if I can add builds
