### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by meichthys** [EightDoor/siyuan#6]
### In what scenarios do you need this feature?

It would be nice to have a full english translation.  (Some docs like the readme are not fully translated)

### Describe the optimal solution

I'm not familiar with how translations usually work in an open source project like this, but i would be very glad to contribute although i'm not a native Chinese speaker. As a start i'd be willing to use google translate or something else to at least translate the readme if that would be a help?

**Comment by EightDoor** [comment]
I will supplement the English documents that have not been translated as soon as possible. The original warehouse has translations of English documents. If you have time, you can also submit a PR
