### ISSUE TITLE
Please add periodic background sync

### ISSUE THREAD

**Issue by parasiteoflife** [EightDoor/siyuan#7]
### In what scenarios do you need this feature?

Everywhere

### Describe the optimal solution

Is the app (desktop and Android) supposed to not periodically sync in the background? For example I create/modify a note in the Android app and it wont show up in the desktop app, I have to manually sync, same the other way around. Is this normal? Does everyone really manually click the sync button every time you maximize the app window? I can't be the only one doing multi-device, right? I'm using wevdav for the sync (sftpgo)

### Describe the candidate solution

Configurable periodic background syncing, like Joplin does (and they also encrypt the notes). I'm fine with it syncing every 5 minutes, but Joplin does real time also, if I create a note it is automatically synced in the desktop app. I guess this could be done creating a file with the device id in a centralized subdir, then touching it (so it updates it modtime) every time something is modified in the device, and in every app periodically scan that subdir for the files modtimes, if a change is detected start syncing.

**Comment by EightDoor** [comment]
New features can be to siyuan request, this repository just go to the user information related to the content, easy to s3 synchronization
